import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Background from "@/components/Background";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { SITE_URL, webApplicationLd } from "@/lib/seo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8001";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Hone — Free AI Resume Checker & ATS Score Analyzer",
    template: "%s — Hone",
  },
  description:
    "Free AI resume checker that scores your resume, flags missing ATS keywords, rewrites weak bullets, and estimates interview odds by company tier. Instant, private, no signup.",
  keywords: [
    "resume checker",
    "ATS resume checker",
    "resume score",
    "AI resume checker",
    "resume analyzer",
    "free resume review",
    "ATS score checker",
  ],
  openGraph: {
    // OG image is generated by app/opengraph-image.tsx (file convention).
    title: "Hone — Free AI Resume Checker & ATS Score Analyzer",
    description:
      "Score your resume, find missing ATS keywords, rewrite weak bullets, and see interview odds by company tier. Free, private, no signup.",
    url: SITE_URL,
    siteName: "Hone",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Hone — Free AI Resume Checker & ATS Score Analyzer",
    description: "Score your resume, fix ATS keywords, rewrite bullets, and see interview odds.",
  },
  alternates: { canonical: "/" },
  robots: { index: true, follow: true },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <link rel="preconnect" href={API_URL} />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(webApplicationLd()) }}
        />
      </head>
      <body className="min-h-full bg-base font-sans text-primary">
        <span id="top" className="absolute top-0" aria-hidden="true" />
        <Background />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
