import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Sora } from "next/font/google";
import "./globals.css";
import Background from "@/components/Background";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SmoothScroll from "@/components/SmoothScroll";
import { SITE_URL, softwareApplicationLd } from "@/lib/seo";

const sora = Sora({
  variable: "--font-display",
  subsets: ["latin"],
  display: "swap",
});

const geist = Geist({
  variable: "--font-body",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-data",
  subsets: ["latin"],
  display: "swap",
});

export const viewport: Viewport = {
  themeColor: "#0a0a0f",
};

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8001";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Free AI Resume Checker & ATS Scanner | ResumeGrading",
    template: "%s — ResumeGrading",
  },
  description:
    "Free AI resume checker that scores your resume, flags missing ATS keywords, rewrites weak bullets, and estimates interview odds by company tier. Instant, private, no signup.",
  openGraph: {
    // OG image is generated by app/opengraph-image.tsx (file convention).
    title: "Free AI Resume Checker & ATS Scanner | ResumeGrading",
    description:
      "Score your resume, find missing ATS keywords, rewrite weak bullets, and see interview odds by company tier. Free, private, no signup.",
    url: SITE_URL,
    siteName: "ResumeGrading",
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "Free AI Resume Checker & ATS Scanner | ResumeGrading",
    description: "Score your resume, fix ATS keywords, rewrite bullets, and see interview odds.",
  },
  // Enables rich link previews on iMessage, WhatsApp, Discord, Slack, LinkedIn
  appleWebApp: { title: "ResumeGrading", statusBarStyle: "black-translucent" },
  alternates: { canonical: "/" },
  robots: { index: true, follow: true },
  verification: { google: "RqnWTXO9UCuN5xSFe2P2GhqReG8jtwaUEmkWNnkwJjo" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sora.variable} ${geist.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <link rel="preconnect" href={API_URL} />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareApplicationLd()) }}
        />
      </head>
      <body className="min-h-full bg-base font-sans text-primary">
        <span id="top" className="absolute top-0" aria-hidden="true" />
        <SmoothScroll />
        <Background />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
